=== madar007/Internet-Programming/Assignment8/Catalog.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema
	xmlns="http://www.cs.umn.edu/4131/ns/catalog"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	targetNamespace="http://www.cs.umn.edu/4131/ns/catalog"
	elementFormDefault="qualified"
	>

	<xsd:annotation> 
		<xsd:documentation xml:lang="en">
			Schema for Course Catalog
		</xsd:documentation>
	</xsd:annotation>
	
	<xsd:element name="courseCatalog" type="courseListType"/>
		<xsd:complexType name="courseListType">
			<xsd:sequence>
				<xsd:element name="course" type="courseType" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
		<xsd:complexType name="courseType">
			<xsd:sequence>
				<xsd:element name="title">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:maxLength value="50"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>
				<xsd:element name="instructor " type="instructorType" minOccurs="1" maxOccurs="3"/>
				<xsd:element name="number" type="courseNumberType"/>
				<xsd:element name="schedule" type="scheduleType"/>
				<xsd:element name="semester" type="semesterType"/>
				<xsd:element name="enrollment" type="enrollmentType"/>
			</xsd:sequence>
		</xsd:complexType>
		<xsd:complexType name="instructorType">
			<xsd:sequence>
				<xsd:element name="firstname" type="xsd:string" />
				<xsd:element name="lastname" type="xsd:string" />
			</xsd:sequence>
			<xsd:attribute name="title" type="personTitleType" use="optional" />
		</xsd:complexType>
		<xsd:simpleType name="personTitleType">
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="Dr"/>
				<xsd:enumeration value="Prof"/>
			</xsd:restriction>
		</xsd:simpleType>
		<xsd:simpleType name="courseNumberType">
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="[A-Z][A-Z][0-9][0-9][0-9][0-9]" />
			</xsd:restriction>
		</xsd:simpleType>
		<xsd:simpleType name="semesterType">
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="Fall"/>
				<xsd:enumeration value="Spring"/>
				<xsd:enumeration value="Summer"/>
			</xsd:restriction>					
		</xsd:simpleType>
		<xsd:simpleType name="lectureHourType">
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="[0-9][0-9]:[0-9][0-9]-[0-9][0-9]:[0-9][0-9]" />
			</xsd:restriction>
		</xsd:simpleType>
		<xsd:complexType name="scheduleType">
			<xsd:sequence>
				<xsd:element name="lecture" type="DayTimeType" minOccurs="1" maxOccurs="3"/>
			</xsd:sequence>
		</xsd:complexType>
		<xsd:complexType name="DayTimeType">
			<xsd:simpleContent>
				<xsd:extension base="lectureHourType">
					<xsd:attribute name="day" use="required" type="WeekdayType"/>
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
		<xsd:simpleType name="WeekdayType">
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="Mon"/>
				<xsd:enumeration value="Tue"/>
				<xsd:enumeration value="Wed"/>
				<xsd:enumeration value="Th"/>
				<xsd:enumeration value="Fri"/>
			</xsd:restriction>
		</xsd:simpleType>
		<xsd:simpleType name="enrollmentType">
			<xsd:restriction base="xsd:integer">
				<xsd:minInclusive value="10"/>
				<xsd:maxInclusive value="100"/>
			</xsd:restriction>
		</xsd:simpleType>
</xsd:schema>

=== madar007/Internet-Programming/Assignment8/Example1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<courseCatalog 
	xmlns="http://www.cs.umn.edu/4131/ns/catalog"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.cs.umn.edu/4131/ns/catalog Catalog.xsd">
	
	<course>
		<title> Operating Systems </title>
		<instructor title="Prof"> 
			<firstname> Tian </firstname> 
			<lastname> He </lastname>
		</instructor> 
		<instructor>
			<firstname> Anand </firstname>
			<lastname> Tripathi </lastname> 
		</instructor>
		<number>CS4061</number> 
		<schedule>
			<lecture day="Tue">04:00-05:15</lecture>
			<lecture day="Th">04:00-05:30</lecture>
		</schedule>
		<semester>Fall</semester>
		<enrollment>100</enrollment> 
	</course>
	
</courseCatalog>

=== madar007/Internet-Programming/Assignment8/Example2.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<courseCatalog 
	xmlns="http://www.cs.umn.edu/4131/ns/catalog"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.cs.umn.edu/4131/ns/catalog Catalog.xsd">
	
	<course>
		<title> Operating Systems </title>
		<instructor title="Prof"> 
			<firstname> Tian </firstname> 
			<lastname> He </lastname>
		</instructor> 
		<instructor>
			<firstname> Anand </firstname>
			<lastname> Tripathi </lastname> 
		</instructor>
		<number>CS4061</number> 
		<schedule>
			<lecture day="Tue">04:00-05:15</lecture>
			<lecture day="Th">04:00-05:30</lecture>
		</schedule>
		<semester>Fall</semester>
		<enrollment>100</enrollment> 
	</course>
	
	<course> 
		<title> Data Mining </title>
		<instructor title="Dr"> 
			<firstname> George </firstname> 
			<lastname> Karypis </lastname>
		</instructor> 
		<instructor>
			<firstname> Vipin </firstname>
			<lastname> Kumar </lastname> 
		</instructor>
		<number>CS5523</number> 
		<schedule>
			<lecture day="Mon">09:45-11:00</lecture>
			<lecture day="Wed">09:45-11:00</lecture>
		</schedule>
		<semester>Spring</semester>
		<enrollment>75</enrollment> 
	</course>
	
	<course> 
		<title> Database Systems </title>
		<instructor title="Prof"> 
			<firstname> Mohammad </firstname> 
			<lastname> Mokbel </lastname>
		</instructor> 
		<instructor>
			<firstname> Chris </firstname>
			<lastname> Dovolis </lastname> 
		</instructor>
		<number>CS4707</number> 
		<schedule>
			<lecture day="Fri">09:00-01:00</lecture>
		</schedule>
		<semester>Summer</semester>
		<enrollment>20</enrollment> 
	</course>
	
</courseCatalog>

=== madar007/Internet-Programming/Assignment8/Example3.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<courseCatalog 
	xmlns="http://www.cs.umn.edu/4131/ns/catalog"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.cs.umn.edu/4131/ns/catalog Catalog.xsd">
	
	<course>
		<title> Networks </title>
		<instructor title="Prof"> 
			<firstname> Tian </firstname> 
			<lastname> He </lastname>
		</instructor>
		<number>CS4211</number> 
		<schedule>
			<lecture day="Th">18:30-21:00</lecture>
		</schedule>
		<semester>Fall</semester>
		<enrollment>90</enrollment> 
	</course>
	
	<course> 
		<title> Computer Graphics </title>
		<instructor title="Dr"> 
			<firstname> Gary </firstname> 
			<lastname> Meyer </lastname>
		</instructor> 
		<instructor>
			<firstname> Carl </firstname>
			<lastname> Sturtivant </lastname> 
		</instructor>
		<number>CS4611</number> 
		<schedule>
			<lecture day="Mon">14:30-15:45</lecture>
			<lecture day="Wed">14:30-15:45</lecture>
		</schedule>
		<semester>Spring</semester>
		<enrollment>30</enrollment> 
	</course>
</courseCatalog>
